reaviz/reaflow

- stories/Basic.stories.tsx
Extend CustomElements Story to show how to dynamically styles nodes, based on their properties.
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
Currently, the custom node story is limited to a `id` based styling. 
Issue Number: #19
Added a property based styling to the story of custom elements. With this change, readers should get a quick understanding …
> Extend CustomElements story

- docs/Advanced/CanvasState.stories.mdx
- docs/Advanced/SharedState.stories.mdx
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 
- https://github.com/reaviz/reaflow/issues/43#issuecomment-774012401
Improved documentation
```
[ ] Yes
[x] No
```
> Add doc about React state immutability

- docs/Advanced/CustomNodes.stories.mdx
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 
- https://github.com/reaviz/reaflow/discussions/34
- https://github.com/reaviz/reaflow/issues/50
- https://github.com/reaviz/reaflow/issues/44
Better documentation regarding `foreignObject` usage
```
[ ] Yes
[x] No
```
> Add advanced documentation for custom nodes (`foreignObject`)

- .storybook/preview.js
- docs/Advanced/ExtendedUtils.stories.mdx
- docs/Advanced/Utils.stories.mdx
- docs/GettingStarted/LinkingNodes.stories.mdx
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 
- https://github.com/reaviz/reaflow/issues/47
- https://github.com/reaviz/reaflow/issues/42
Documentation improved.
```
[ ] Yes
[x] No
```
Fixes https://github.com/reaviz/reaflow/issues/42
Removed unused storybook config.
> Improve Linking Nodes documentation example + add extended helpers

- .gitignore
- docs/GettingStarted/DataShapes.stories.mdx
- package.json
- src/Canvas.tsx
- src/helpers/useProximity.ts
- src/helpers/useSelection.ts
- src/helpers/useUndo.ts
- src/layout/elkLayout.ts
- src/layout/useLayout.ts
- src/types.ts
- src/utils/CanvasProvider.tsx
- src/utils/useNodeDrag.ts
Ready to be merged
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Updating TS doc mostly with (internal) variable names that make more sense for newcomers. No breaking change. Also added documentation related to ELK to soften the DX.
```
[ ] Yes
[x] No
```
> Improve TS documentation

- README.md
- docs/Community.stories.mdx
- docs/Contributing.stories.mdx
- docs/GettingStarted/SSRSupport.stories.mdx
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/reaviz/reaflow/issues/41
Improved documentation (README)
```
[ ] Yes
[x] No
```
> Add Next.js example + improve existing example + Add community use-cases

- docs/Plugins.stories.mdx
- package.json
- stories/Controls.stories.tsx
- yarn.lock
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
Added an example on how to integrate a more intuitive zooming and panning via [react-zoom-pan-pinch](https://github.com/prc5/react-zoom-pan-pinch).
[Related discussion](https://github.com/reaviz/reaflow/discussions/36)
```
[ ] Yes
[X] No
```
> Add zoom example with react-zoom-pan-pinch

- .eslintrc.js
- src/Canvas.tsx
- src/symbols/Node/Node.tsx
- src/utils/helpers.test.ts
- src/utils/helpers.ts
- src/utils/useEdgeDrag.ts
- src/utils/useNodeDrag.ts
- stories/Drag.stories.tsx
```
[x] Bugfix
[ ] Feature
```
Currently nested nodes (nodes having a parent) are unable to be rearranged. Similarly, nodes which have children are unable to be rearranged
Find nodes that are nested within other nodes when attempting to drag. If dragging a node containing other nodes, generate JSX for the children. Remove styling of `unlinkable` on dragging nodes. Allow callbacks for `dragNode` and `dragEdge`. Allow dragging a nested node outside of …
> Nested drag

- src/Canvas.tsx
```
[x] Bugfix
[ ] Feature
```
There is an unneeded dependency on a useEffect which is causing it to be triggered when not needed.
Remove the unneeded dependency to stop triggering the useEffect
```
[ ] Yes
[x] No
```
> remove unneeded dependency

- stories/Drag.stories.tsx
```
[x] Bugfix
[ ] Feature
```
Unable to drag nested node to node after and could drag node to one above
Fix `hasLink` check
```
[ ] Yes
[x] No
```
> fix hasLink check in nested drag story

- docs/Helpers/Undo.stories.mdx
- src/helpers/useUndo.ts
- stories/Undo.stories.tsx
```
[x] Bugfix
[ ] Feature
```
count() and history() throws "TypeError: Cannot read property '_history' of undefined",
clear() cleaning current tree
Issue Number: #66 
count() return number of possible undos,
history() return array of previous states,
clear(nodes, edges) clean history and make first element of new history with current nodes and edges
```
[ ] Yes
[x] No
```
> fix useUndo functions(count, history, clear)

- src/symbols/Node/Node.tsx
```
[x] Bugfix
[ ] Feature
```
Тow, even if handlers for node events are not passed, events are processed and unnecessary re-renders occur
Added check if event handler is passed
```
[ ] Yes
[x] No
```
> fix unnecessary re-renders

- src/Canvas.tsx
- src/layout/elkLayout.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 134, 101
Data is re added to edge
```
[ ] Yes
[ ] No
```
> Fix data attribute in edge

- src/symbols/Node/Node.tsx
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Fixes missing data in nested edges

- src/symbols/Edge/Edge.tsx
```
[ ] Bugfix
[X] Feature
```
The  Edge label can receive the context of the edge including the data
```
[ ] Yes
[ ] No
```
> Edge labels extra data

- .storybook/main.js
- src/Canvas.tsx
- src/symbols/Add/Add.tsx
- src/symbols/Node/Node.tsx
- src/symbols/Port/Port.tsx
- src/symbols/Remove/Remove.tsx
- stories/Editor.stories.tsx
- stories/Proximity.stories.tsx
```
[ ] Bugfix
[ ] Feature
```
Create React Apps that depend on this lib were failing because of the `/dist/` import. removing the dist import broked storybook. This fixes both
```
[ ] Yes
[ ] No
```
> Fix story book and CRA

- package.json
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Uses latest rdk version
```
[ ] Yes
[ ] No
```
> dump rdk version

- docs/Community.stories.mdx
Added a new community project
```
[ ] Bugfix
[ ] Feature
```
> Add JSON Visio to Community Projects

- src/symbols/Label/Label.tsx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> [139] added tooltip on hover

- src/symbols/Node/Node.tsx
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: improved typings
```
Currently, `NodeProps` has a properties field that is of type `any`.
See #172 
Added correct typings
```
[ ] Yes
[x] No
```
> improve NodeProps typings

- src/Canvas.tsx
```
[ ] Bugfix
[ ] Feature
```
The JSDoc comment of the `<Canvas>` element `onNodeLink()` property reports the description of the `onNodeLinkCheck()` property (and viceversa)
The documentation comments have been switched.
```
[ ] Yes
[x] No
```
> Fix Canvas `onNodeLink` documentation

- src/layout/utils.ts
> Revert "Fix webpack error"

- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: package upgrade
```
```
[ ] Yes
[x] No
```
> Upgrade framer

- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: chore
```
```
[ ] Yes
[x] No
```
> Upgrade reakeys + reablocks

- src/symbols/Edge/Edge.tsx
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
```
> Migrate Edge default props

- package-lock.json
- package.json
- stories/Node.stories.tsx
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
update motion and broken icons
Issue Number: GOOD-565
```
[ ] Yes
[x] No
```
> GOOD-565 update motion and broken icons
