reaviz/reaflow

src/layout/elkLayout.ts, src/layout/utils.test.ts, src/layout/utils.ts, src/types.ts, stories/Basic.stories.tsx, stories/Nested.stories.tsx
```
[ ] Bugfix
[X] Feature
[X] Documentation content changes
```
The node content might get "covered" by nested nodes and there is currently no way to provide a padding for nodes within a node.
Issue Number: #28 
The padding towards nested nodes can now be adjusted for individual nodes.
```
[ ] Yes
[X] No
```
Naming might be ambigous - Open for suggestions! maybe "innerPadding" or "nestedPadding" is more intuitive, because the actual node content is not affected by the padding.
=> Add adjustable padding for nested nodes and add storybook story for custom nested nodes

package.json, src/helpers/crudHelpers.test.ts, src/helpers/crudHelpers.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: [#37]
Newly created edges from `upsertNode` will take properties from the original edge and will be inserted in the right place
```
[ ] Yes
[x] No
```
=> adjust the `upsertNode` function to update edges that are within groups

src/symbols/Edge/Edge.tsx, src/symbols/Node/Node.module.css, src/symbols/Node/Node.tsx, src/symbols/Port/Port.tsx
```
[ ] Bugfix
[x] Feature
```
Using `children` isn't currently possible for Edge/Port components.
Issue Number: 
- #67
Using `children` is now possible for Edge/Port components.
```
[ ] Yes
[x] No
```
New capabilities:
- Using `children` to display custom React components at the center of an edge.
- Using `children` to display custom React components close to a port.
Used by https://github.com/Vadorequest/poc-nextjs-reaflow/pull/4 to display the following:
---
Depends …
=> Add `children` property to Edges/Port components

src/Canvas.tsx, stories/Nested.stories.tsx
```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Issue Number: https://github.com/reaviz/reaflow/issues/80
No visible change other than it actually works with what i called "deeply nested edges". The bug, however, is being adressed upstream, but it provides a temporary fix to the issue with deeply nested edges. Also i've changed the order, so edges are always drawn on top, rather than behind nodes. The example is also edited to include a so called "deeply nested edge"
```
[ ] Yes
[x] No …
```
=> Error state

src/Canvas.tsx, stories/Drag.stories.tsx
```
[x] Bugfix
[ ] Feature
```
Error is thrown when a dragNode or dragEdge callback is used for overriding the drag.
Remove `dragEdge` callback option. Get the node props of the dragging node to use with the `dragNode` callback function.
```
[ ] Yes
[x] No
```
=> Drag node edge callback

src/utils/helpers.ts, stories/Drag.stories.tsx
```
[x] Bugfix
[ ] Feature
```
Nodes that are nested within a nested node cannot be dragged due to findNestedNode returning on an empty object instead of a node object.
Properly return when a child node is actually found.
```
[ ] Yes
[x] No
```
=> fix finding deeply nested nodes

src/Canvas.tsx
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
When passing children to the <Edge> component as a prop of Canvas, the children get ignored because cloneElement does not copy the children prop. It needs to be explicitly passed along, this was done for the Node case, but not for the Edge case.
When passing children to the <Edge> …
=> Pass children to edge cloned element

src/symbols/Edge/Edge.module.css, src/symbols/Edge/Edge.tsx, src/types.ts
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
it's not possible to style "hover" status for edge.
Issue Number: #138 
now main Edge component - "g" takes a class "mainClassName", and since the hover fires on "g" you can style the edge itself ("path" element) now. Only with !important due to the weight of the selectors, but this is already something. …
=> improve edge custom styling

src/Canvas.tsx
```
[x] Bugfix
[ ] Feature
```
According to [docs](https://reaflow.dev/?path=/story/demos-edges--no-arrows), arrow supposedly can have the `null` value but it's type prevents that.
Allow `null` for arrow prop
```
[ ] Yes
[x] No
```
=> Fix incorrect prop type (arrow)

src/symbols/Edge/Edge.tsx
```
[x ] Bugfix
[ ] Feature
```
Issue Number: 164
It is now possible to set a new property: 'interpolation', using enums 'linear' or 'curve', or by passing an interpolation function similar to the ones defined [here](https://github.com/d3/d3-shape/blob/main/README.md#curves)
```
[ ] Yes
[ x] No
```
The default value 'curve' retains the original behaviour
=> Added interpolation props to Edge

src/Canvas.tsx, src/layout/useLayout.ts
```
[ ] Bugfix
[x] Feature
```
Currently, you cannot set scroll position using any exported method and hence cannot focus or centre around a node using x/y, based on our own business logic.
See [#64](https://github.com/reaviz/reaflow/issues/64#issuecomment-779863073)
This PR exposes the setScrollXY and makes it available in the useLayout hook and canvas ref.
We tested it in our app, and it is working fine for searching and focusing on a specific node: …
=> Feature/expose useScrollXY function

package.json, yarn.lock
This bump fixes some issues with `g is not defined`
Tested it locally, let me know if there's anything wrong that can possibly happen.
```
[X] Bugfix
[ ] Feature
```
https://github.com/reaviz/reaflow/issues/91
There's no `window.g is not defined` error
```
[ ] Yes
[X] No
```
=> Bump elkjs version

src/utils/helpers.ts, src/utils/useNodeDrag.ts
This is related to the last PR I made: https://github.com/reaviz/reaflow/pull/154
```
[x] Bugfix
[ ] Feature
```
When the `position` is not `center`, `getCoords` returns the wrong transformation, and so the drag edge does not point to the cursor
The drag edge always follows the cursor correctly when various `position`'s are used. After doing some light algebra, it turns out `getCoords` could be greatly simplified by using the `xy` from `useLayout`, which already takes `position` into account.
```
[ ] Yes
[x] No
```
=> Fix getCoords when non-center position is used

src/helpers/useProximity.ts
```
[x] Bugfix
[ ] Feature
```
Error with useProximity when dragging a node
Issue Number: https://github.com/reaviz/reaflow/issues/198
Use proper getCoords call within useProximity to prevent error
```
[ ] Yes
[x] No
```
=> update useProximity getCoords call

src/layout/utils.ts
Fixes #225
Fixes #228
For some reason `calculateSize` can be accessed via `.default`
```
[x] Bugfix
[ ] Feature
```
I'd recommend trying locally before merging.
=> Fix webpack error

src/layout/utils.ts
Fixes #229 
Added check for function as calculateSize always exists and `default` cannot be set
=> fix: calculateSize fn

src/layout/elkLayout.ts
Objective: Since 5.2.0 switch to Vite, the dist folder has become a type=module. But at this line 18: the bundled code is referenced directly without extension. Adding the extension resolves webpack resolution error when using reaflow as library.
Functionally, there would be no change introduced.
```
[x] Bugfix
[ ] Feature
```
Resolves #223 without adding webpack config change.
Issue Number: #223 
```
[ ] Yes
[x] No
```
=> fix: elk.bundled webpack error

src/layout/elkLayout.ts
This fixes the width calculation for horizontal edge labels so they're centered
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improvement
```
Horizontal edge labels are to the right of center along the edge/line connecting two nodes. This is more obvious the longer the label is
Horizontal edge labels are now centered along the edge
```
[ ] Yes
[x] No
```
**BEFORE**
**AFTER**
=> fix: Center horizontal edge labels

docs/Advanced/Refs.mdx, src/Canvas.tsx, src/utils/useZoom.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improvement
```
Charts tend to zoom much faster on trackpads than mouse wheels (when using panType=drag)
Chart zooming feels consistent across input devices
```
[ ] Yes
[x] No
```
This determines zoom strength based off the amount of pixels in the scroll event delta's instead of the amount of scroll events sent (trackpads send alot of little scrolls, mouse wheels send fewer larger scrolls)
=> Improve scroll consistency on diff devices

src/Canvas.module.css, src/Canvas.tsx
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improvement
```
There's no visual indication that you can drag the canvas to pan
Grab and grabbing cursor is used for drag panning
```
[ ] Yes
[x] No
```
BEFORE
https://github.com/reaviz/reaflow/assets/40581813/809f1ba4-2b7d-4631-866a-6d6382814349
AFTER
https://github.com/reaviz/reaflow/assets/40581813/737026cf-137e-475e-9e00-0896109dade7
=> Update pan drag cursor
